### ISSUE TITLE
Взлом шкафчиков и ящиков.

### ISSUE THREAD

**Issue by Aylong220** [ss220club/Paradise-Remake#124]
Все жалуются что на старопаре и то и то взламывалось, а тут нет.

**Comment by BR54FF** [comment]
Будет лишним усилением антагов сейчас, как по мне

**Comment by Aylong220** [comment]
Возможно, но неломаемый ящик - рофлан ебало, минут 10 в 3 рыла колупали, а ему хоть бы хны
